### ISSUE TITLE
Argument for non rounded diff

### ISSUE THREAD

**Issue by fehergeri13** [gf3/moment-range#104]
In momentjs by default, `moment#diff` will return number rounded down. If you want the floating point number, pass true as the third argument. In moment-range this should work the same.

```
DateRange.prototype.diff = function(unit, rounded) {
    var _rounded = (arguments.length === 1 || rounded === undefined) ? false : rounded;
    return this.end.diff(this.start, unit, _rounded);
};
```

**Comment by gf3** [comment]
excellent suggestion, this is addressed in the upcoming v3 release

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
