### ISSUE TITLE
Add documentation for getting the start / end date from a range

### ISSUE THREAD

**Issue by edu2004eu** [gf3/moment-range#107]
There's no explanation in the docs on how to get the start and end date from a range. Even though it's kind of logical to try to get the `.start` and `.end` properties on a range, it's not explicitly written anywhere (hence, people might think it's not implemented at all). The only instance of a reference to `.start` is within the `clone()` example.

Please consider adding this to the documentation. Thanks.

**Comment by carueda** [comment]
+1

**Comment by gf3** [comment]
good call

**Comment by gf3** [comment]
added in the upcoming `3.0.0` release → https://github.com/gf3/moment-range/blob/da7da21ca4b5a6293078a0189caebec5b7c48120/README.md#attributes

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
