### ISSUE TITLE
.toArray outputs to Moment's array

### ISSUE THREAD

**Issue by simonered** [gf3/moment-range#111]
Maybe a typo in documentation, maybe I misunderstood...but **.toArray()** method outputs to an array of **Moment** object **not Date**.

Here is a  [pen](http://codepen.io/simonered/pen/ZWeyJX).

**Comment by jamesaspence** [comment]
TBH I like this, but I think either the documentation needs to be updated or the method changed.

Preferably, something like `range.toArray('day', false)` to return moment instead of dates would be great. Or `range.toMomentArray('day')`.

**Comment by xtrasmal** [comment]
It works, but you need to understand that you will always get an instance when you do not explicitly run a ```format()```.

I've updated the code in your pen
```javascript
var range = moment.range(moment(), moment().add(7, 'days'));

var arr = range.toArray('days');

var idx, text = "";

for (idx in arr) {
  var date = arr[idx];
  text += moment(date).format('DD MM YYYY') + '<br>';
}
```

**Comment by jamesaspence** [comment]
That's the point though - the documentation clearly says _to an `Array` of `Date` objects_. This is incorrect; the method produces an `Array` of `Moment` objects, and therefore needs updating.

**Comment by siboulet** [comment]
Ran into this issue as well. The new toArray() function return moment objects, not date objects. Documentation needs to be updated.

**Comment by gf3** [comment]
`toArray` is going away in the upcoming v3 release in favour of `by`, `byRange`, `reverseBy`, and `reverseByRange`. these new methods return iterators which you can use to grab an array or just what you need. here's an example:

``` js
const d1 = new Date(Date.UTC(2011, 1, 1));
const d2 = new Date(Date.UTC(2013, 1, 1));
const range = moment.range(d1, d2);

const array = Array.from(range.by('years'));
const years = array.map(m => m.utc().year());

expect(years).to.eql([2011, 2012, 2013]); // true
```

lots of fun examples [here](https://github.com/gf3/moment-range/blob/3a5d06cb2d9c44a060f9515a91deb984c7c269de/lib/moment-range_test.js#L136)

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions

**Comment by giohappy** [comment]
it's a pity you removed .toArray() because Array.from hasn't wide support yet...
