### ISSUE TITLE
Why don't ranges intersect on boundaries?

### ISSUE THREAD

**Issue by CExWHamdan** [gf3/moment-range#112]
Consider the below example:

``` javascript
var a = moment('28-Mar-2016')
var b = moment('29-Mar-2016')
var c = moment('29-Mar-2016')
var d = moment('30-Mar-2016')

var range1 = moment.range(a, b)
var range2 = moment.range(c, d)

range1.intersect(range2) // returns null
```

One would assume that range1 and range2 actually intersect at '29-Mar-2016'. Is this behaviour intended and do you mind explaining why?

**Comment by StevenRKM** [comment]
It's an intersection if you include the endpoints. 
An optional parameter for this inclusion could be provided, like it is used with the 'contains' method. However then it is very important to check the return value, it could be undefined, a Moment or a MomentRange.
To avoid this confusion it 's maybe better to provide an additional  method that checks if two intervals touch eachother.

**Comment by stevesims** [comment]
+1 on this from me

would be very handy to find out if two moments are adjacent

**Comment by gf3** [comment]
great suggestions, i've added both an [`#adjacent`](https://github.com/gf3/moment-range/blob/25be063e539de84f1e4884b776a9bb0a10d9f52f/lib/moment-range.js#L52-L57) method and an [`adjacent option to #overlaps`](https://github.com/gf3/moment-range/blob/25be063e539de84f1e4884b776a9bb0a10d9f52f/lib/moment-range.js#L193-L201) in the upcoming release

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions

**Comment by tncbbthositg** [comment]
I feel like I might be missing something.  I still have this issue with 4.0.2.
