### ISSUE TITLE
Suggestion: .by should support a moment.duration object

### ISSUE THREAD

**Issue by stevesims** [gf3/moment-range#114]
Documentation for the `.by` method says that "any of the units accepted by moment.js's `add` method" can be used, however whilst `add` will support a duration, `by` does not.

Being able to iterate by an arbitrary duration would be very useful.  Right now for me this is the only significant deficiency in moment-range when compared to twix.

**Comment by enrichman** [comment]
+1 :+1: 
I was looking for the same functionality. RIght nnow I have to use a manual moment iteration.

**Comment by gf3** [comment]
excellent suggestion—this is fixed in the upcoming v3 release and [even has tests](https://github.com/gf3/moment-range/blob/0c7077fc42827c9f7790a99101e11b721d59a438/lib/moment-range_test.js#L397-L408)

**Comment by stevesims** [comment]
sweet 😀 👍

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
