### ISSUE TITLE
minification breaks moment-range

### ISSUE THREAD

**Issue by dawsonbotsford** [gf3/moment-range#117]
Peer dependencies break minification since `moment` is changed to be a different variable name. 

Has there been an effort into creating a wrapper function to wrap an existing `moment` object in `moment-range` functions? That API would then be:

``` js
var _moment = require('moment');
var moment = require('moment-range')(moment);
```

**Comment by gf3** [comment]
excellent suggestion—this is [being addressed the upcoming v3 release](https://github.com/gf3/moment-range/blob/f6517c606e2216805b7552577ab741e08b97a516/lib/moment-range.js#L273-L303):

``` js
import M from 'moment';
import { DateRange, extendMoment } from './moment-range';

const moment = extendMoment(M);
```

**Comment by dawsonbotsford** [comment]
We solved this months ago with dependency injection. Let me know if this get's rolled into the project and we'd be happy to switch back to this. [Here's what worked for us](https://github.com/dawsonbotsford/moment-range/commit/f8fd770dddb8a3ba3bf444e35993c2a11b6cf886)

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
