### ISSUE TITLE
package.json's `main` points to `dist`

### ISSUE THREAD

**Issue by andywer** [gf3/moment-range#118]
Hi there!
We are working on a webpack / system.js hybrid here. Webpack creates multiple bundles which can then be loaded dynamically using System.js.

Problem is that the UMD header of `dist/moment-range.js` (created by `grunt-umd`) checks for AMD's `define` first and for common-js `module.exports` after. System.js provides a define(), so it uses this, but we rather want to use common-js (in our case bundled by webpack).

**Other packages usually point to `lib/` in `package.json`'s `main` and/or check for common-js first in their UMD headers.**

Would you mind either pointing `main` to `lib/` or use another UMD header?
I think by today's standards common-js modules should be the default and it would really help us using your library. Especially since it's used by many other packages, too.

Thx!

**Comment by gf3** [comment]
thanks for the suggestion, i'm using a new UMD packager in the upcoming v3 release that should solve this! stay tuned

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
