### ISSUE TITLE
feature: allow flooring option for bucketizing

### ISSUE THREAD

**Issue by ilovett** [gf3/moment-range#122]
Example:

On a range of 12:30 pm Jul 1 - 4:30pm Jul 4

iteration 1: Start from 12:30 pm Jul 1
iteration 2: Start from 12:00 am Jul 2 // round down day to midnight
iteration 3: Start from 12:00 am Jul 3
iteration 4: Start from 12:00 am Jul 4

**Comment by gf3** [comment]
this should be straight-forward in the upcoming v3 release:

``` js
const M = require('moment');
const MR = require('./dist/moment-range');
const moment = MR.extendMoment(M);

const dr = moment.range('2016-07-01T12:30', '2016-07-04T16:30');
const arr = Array.from(dr.by('days'));

arr.map(m => m.startOf('day').add(12, 'hours'))
```

<img width="564" alt="screen shot 2016-12-07 at 9 59 28 pm" src="https://cloud.githubusercontent.com/assets/18397/20995977/75bbafc0-bcc8-11e6-9ce3-dc130f74bb9f.png">

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
