### ISSUE TITLE
Cannot import via browserify

### ISSUE THREAD

**Issue by royipr** [gf3/moment-range#123]
Hi

I could find a way to use this library with browesrify.
`Cannot find module 'moment'` 
Important to say that i was able to import other libs that depend on `moment` 

I was able to fix the problem by [Changing  this line ](https://github.com/gf3/moment-range/blob/master/dist/moment-range.js#L11) to `module.exports = factory(moment)`

Any ideas how to fix this properly without this hack

**Comment by gf3** [comment]
hopefully this should be fixed in the upcoming v3 release, i've switched to build tool to use something more reliable for generating UMD libraries

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
