### ISSUE TITLE
Possible performance improvement

### ISSUE THREAD

**Issue by der-cain** [gf3/moment-range#124]
Hi all,

I am using moment range and it is very helpful, thanks a lot for the great work!

I am creating a lot of ranges in an inner loop and I noticed that in line 355 of moment-range.js this function 

```
moment.range = function(start, end) {
  if (start in INTERVALS) {
    return new DateRange(moment(this).startOf(start), moment(this).endOf(start));
  }
  else {
    return new DateRange(start, end);
  }
};
```

converta the moment into a string every time, which causes lots of overhead. Would it be possible to check before if start is actually a string? IE

`!start instanceof moment && start in INTERVALS`

Thanks!

BR,
Marius

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
