### ISSUE TITLE
moment#within does not work with moment-timezone correctly

### ISSUE THREAD

**Issue by basicdays** [gf3/moment-range#127]
Hey all,

Just ran into a bug with `moment-range` and `monent-timezone`. With `moment-timezone`, it looks like it uses the internal `moment#_d` property to match what the timezone setting is for the moment instance. Calling `moment#toDate()` seems to produce the corrected `Date` instance without timezone altering.

However, `moment#within` seems to explicitly pass `moment#_d` to `DateRange#contains`, which is going to be the incorrect `Date` object, since it was altered by timezones. It seems making the following change both solves that problem and doesn't break any existing tests:

```
moment.fn.within = function(range) {
  return range.contains(this._d);
};
```

to

```
moment.fn.within = function(range) {
  return range.contains(this.toDate());
};
```

If this seems ok, I can submit a PR?

**Comment by gf3** [comment]
excellent suggestion, this is addressed in the upcoming v3 release

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
