### ISSUE TITLE
'quarter' unit not working for range construction

### ISSUE THREAD

**Issue by kanedaki** [gf3/moment-range#134]
How to reproduce:

var date = moment()
date.range('quarter').toString()
"Invalid date/2016-12-09T12:19:01+01:00"

Thanks for this library. It's been very useful so far

**Comment by gf3** [comment]
thanks for the bug report, i've fixed this in the upcoming release:

<img width="571" alt="screen shot 2016-12-12 at 11 15 25 am" src="https://cloud.githubusercontent.com/assets/18397/21106555/868b7c58-c05c-11e6-9dde-44faf3e6b99f.png">

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
