### ISSUE TITLE
Add tips in documentation on range.contains for using .startOf() / .endOf()

### ISSUE THREAD

**Issue by seanwendt** [gf3/moment-range#136]
There are some gotchas that made using ranges a little tricky for me at first, while working with dates that fall on the end of a range.  For example, given: 
```
start = moment("2016-12-20", "YYYY-MM-DD")
end = moment("2016-12-20", "YYYY-MM-DD")
range =  moment.range(start, end)

today = moment()    // assuming it's 2016-12-20
range.contains(today)    // returns false. --huh?

today = moment().startOf('day')    // still assuming it's 2016-12-20
range.contains(today)    // returns true. --oh.
```

Similarly, if we change end to:
`end = moment("2016-12-20", "YYYY-MM-DD").endOf('day')`

```
today = moment()    // assuming it's 2016-12-20
range.contains(today)    // returns true
```

This should probably be more clearly documented in the moment.js documentation to be fair, but it might be helpful to briefly mention these peculiarities in the readme here.

Thanks!

**Comment by gf3** [comment]
thanks for the feedback, @seanwendt, any suggestions on how it might be worded to prevent confusion?

**Comment by seanwendt** [comment]
Hey @gf3 ,  I might add this at line 118 of the README.md?

_Note_: Dates and moment objects both use a timestamp of 00:00 if none is provided.  To ensure your range includes any timestamp for the given end date, use `.setHours(23,59,59,999)` when constructing a Date object, or `.endOf('day')` when constructing a moment object.

**Comment by gf3** [comment]
thanks @seanwendt

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
