### ISSUE TITLE
Which is the latest version?

### ISSUE THREAD

**Issue by jaapz** [gf3/moment-range#139]
I see you recently released version 3.0.0-0, but it's not in the master branch yet.
Does the `-0` mean it's still in alpha or beta phase?
Currently `npm outdated` flags your package as outdated, which is a bit weird if the 3.0.0 is not yet out as a stable version.

Maybe you need to add `-alpha.0` instead (as that is what semver.org proposes).

**Comment by gf3** [comment]
that's odd because i used npm itself to cut a pre-release via `npm version premajor`

**Comment by gf3** [comment]
[`3.0.0`](https://github.com/gf3/moment-range/releases/tag/v3.0.0) has been released!
