### ISSUE TITLE
API documentation link broken

### ISSUE THREAD

**Issue by Roger-Waters** [gf3/moment-range#140]
[Detailed API documentation](http://gf3.github.io/moment-range/DateRange.html) link is broken (Error 404)

**Comment by gf3** [comment]
@Roger-Waters ahh sorry—i removed that a little preemptively in anticipation of the upcoming [3.0.0](https://github.com/gf3/moment-range/pull/138) release. check out the README for docs on the new usage

**Comment by Roger-Waters** [comment]
May be it has sense to remove this link from README at all?

**Comment by gf3** [comment]
@Roger-Waters definitely

**Comment by gf3** [comment]
done!
