### ISSUE TITLE
v3 doesn't work with bower.  Still supported?

### ISSUE THREAD

**Issue by mtraynham** [gf3/moment-range#143]
You aren't committing the ES5 distribution into the repo, nor including a bower.json file that would point at the distribution.  I assume this is why you have webpack though...  Can you advise?

**Edit** Just saw the release notes.  We could likely still install with bower if you included the webpack distribution in the repo.

**Comment by gf3** [comment]
@mtraynham indeed—this is deliberate since the need for bower is dwindling out. for now you'll need to lock bower to the old version (`2.2.0`)

**Comment by mtraynham** [comment]
I don't disagree with that sentiment, but I'm stuck with bower atm.  So thanks for the info.
