### ISSUE TITLE
Please include lib in npm release

### ISSUE THREAD

**Issue by victoriafrench** [gf3/moment-range#149]
Please include the `lib` in the npm release and add the following to package.json:

```
     "module": "lib/moment-range.js"
```

Currently you are shipping `main` which is a webpacked version. Those of us using alternative bundlers (I am using rollup) have issues with named exports from webpack. The `modules` directive tells the bundlers where the es6 version of the code is. It also enables our bundlers to tree shake.

Rollup uses the following paths in this order:
`jsnext:main` -> usually stage-* code
`module` -> usually ES6/node reference point
`main` -> usually transpiled code
finally the `bin` directory

Thanks

**Comment by gf3** [comment]
this has been released in `3.0.2`

**Comment by victoriafrench** [comment]
Thank you, just pulled and it imported beautifully.

**Comment by p-j** [comment]
This broke Webpack builds: https://github.com/gf3/moment-range/issues/153
