### ISSUE TITLE
Change Calendar-Based Rule: ranges: daysOfWeek

### ISSUE THREAD

**Issue by poing** [gf3/moment-range#160]
I am trying to change daysOfWeek rules.  The source data I am working with uses 1-7.  
But it's unclear how I can make this change.  This is what I have so far, but the documentation is lacking details.  
```javascript
moment().recur({
    rules: [
        { units: { low: 1, high: 7 }, measure: "daysOfWeek" }
    ]
});
```

**Comment by gf3** [comment]
@poing did you mean to open this issue on https://github.com/moment/moment/ ?

**Comment by poing** [comment]
No, I wanted to ask how to change the moment-recur -> Calendar -> ranges -> daysOfWeek

**Comment by gf3** [comment]
@poing there's no `recur` or `daysOfWeek` in this library. perhaps you mean this one: https://github.com/c-trimm/moment-recur ?

**Comment by poing** [comment]
Line 86.
https://github.com/c-trimm/moment-recur/blob/master/moment-recur.js

**Comment by gf3** [comment]
@poing that is a completely different project

**Comment by poing** [comment]
Oh!
I'm soooooo sorry!
Seems I missed my target!

**Comment by poing** [comment]
I am an ID 10 Tango

**Comment by gf3** [comment]
👍
