### ISSUE TITLE
A range should be considered overlapping even if start and end dates are the same

### ISSUE THREAD

**Issue by ruthmholtrop** [gf3/moment-range#53]
If a range with the same start and end date is within a second range, the overlaps method should return true.

Example:

            var start = new Date(2012, 4, 1)
                , end   = new Date(2012, 4, 23)
                , range = moment().range(start, end);

            var start2 = new Date(2012, 4, 23)
                , end2   = new Date(2012, 4, 26)
                , range2 = moment().range(start2, end2);

            var start3 = new Date(2012, 4, 2)
                , end3   = new Date(2012, 4, 3)
                , range3 = moment().range(start3, end3);

            var start4 = new Date(2012, 4, 2)
                , end4   = new Date(2012, 4, 2)
                , range4 = moment().range(start4, end4);

            console.log(range.overlaps(range2)); // false
            console.log(range.overlaps(range3)); // true
            console.log(range.overlaps(range4)); // should be true
            console.log(range4.overlaps(range)); // should true

**Comment by vptcnt** [comment]
+1

**Comment by gf3** [comment]
fixed in [`1.0.7`](https://github.com/gf3/moment-range/releases/tag/1.0.7)

**Comment by gf3** [comment]
![screen shot 2015-02-25 at 6 15 14 pm](https://cloud.githubusercontent.com/assets/18397/6382863/52b5063e-bd1a-11e4-931f-d1c8789b59f6.png)
