### ISSUE TITLE
Node: Use moment-range with moment-timezone?

### ISSUE THREAD

**Issue by soulhuntre** [gf3/moment-range#54]
Can you clarify in the documents how these things can be used together, or if they must not be used together?

If I:

    moment = require('moment-timezone'),            // Time / Timezone handling
    moment_range = require('moment-range'),                // Time range handling

I get two separate libraries, both extending moment. It is workable, but complicates my code a bit.

Thanks!

**Comment by contra** [comment]
+1 this just rekt me, silent failure when passing in a moment-timezone moment date

**Comment by alexiskattan** [comment]
+1

**Comment by gf3** [comment]
btw this was fixed in `1.1.0`/`1.1.1`. now you'll need to require moment before moment-range, e.g.:

``` javascript
var moment = require('moment');
var DateRange = require('moment-range');
```

**Comment by gf3** [comment]
**Note:** this breaking change was reverted in `1.2.0` and reintroduced in `2.0.0`

**Comment by contra** [comment]
thank u based @gf3

**Comment by gf3** [comment]
h0llaaaaaa

**Comment by ozum** [comment]
Could you provide an example, what is the correct way to use moment-range with moment-timezone right now?

**Comment by gf3** [comment]
@ozum it looks like `moment-timezone` hasn't switched over to use npm peer dependencies yet; which it'll need to do to be _fully_ compatible. i might try opening an issue on their repo with that recommendation

**Comment by gf3** [comment]
@ozum but ideally it would look like this:

``` javascript
var moment = require('moment');
require('moment-range');
require('moment-timezone');
```

**Comment by dmacosta** [comment]
I had the same issue. As a workaround I converted dates to vanilla dates to pass to `range`:

```javascript
var startDate = moment('8:00 am', 'HH:mm a');
var endDate = moment('1:00 am', 'HH:mm a').add(1, 'day');
var range = moment.range(startDate.toDate(), endDate.toDate());

var inRange = range.contains(when.toDate());
```
