### ISSUE TITLE
Range diffs for months are incorrect.

### ISSUE THREAD

**Issue by jiaweihli** [gf3/moment-range#56]
``` coffee
coffee> moment(+new Date('Mon Sep 01 2014 00:00:00')).add(2, 'months').format('ddd MMM D YYYY HH:mm:ss')
'Sat Nov 1 2014 00:00:00'

coffee> moment.range(+new Date('Mon Sep 01 2014 00:00:00'), +new Date('Sat Oct 31 2014 00:00:00')).diff('months')
1
coffee> moment.range(+new Date('Mon Sep 01 2014 00:00:00'), +new Date('Sat Oct 31 2014 23:59:59')).diff('months')
2
coffee> moment.range(+new Date('Mon Sep 01 2014 00:00:00'), +new Date('Sat Oct 31 2014 12:00:00')).diff('months')
2
coffee> moment.range(+new Date('Mon Sep 01 2014 00:00:00'), +new Date('Sat Oct 31 2014 11:59:59')).diff('months')
1
```

Diffs seem to be calculated through the middle instead of the end of the last day.

**Comment by gf3** [comment]
sorry for the delay, @jiaweihli, having trouble reproducing the issue on the latest version:

![screen shot 2015-02-25 at 6 18 19 pm](https://cloud.githubusercontent.com/assets/18397/6382917/cf915cca-bd1a-11e4-955f-531dec9f230f.png)

possibly a timezone issue?

**Comment by jiaweihli** [comment]
Hmm...I'm still running into this.  Not sure how this is a timezone issue, can you try using UTC timestamps?:

![screen shot 2015-02-25 at 3 31 20 pm](https://cloud.githubusercontent.com/assets/351887/6383170/7cc23e72-bd03-11e4-8ed8-6bb6ce255238.png)

**Comment by gf3** [comment]
@jiaweihli just to be sure, what timezone are you in?

**Comment by jiaweihli** [comment]
I'm in PST.

**Comment by gf3** [comment]
can you do the following for me and paste back the output:

```node
> start = new Date(2014, 9, 1)
Wed Oct 01 2014 00:00:00 GMT-0400 (EDT)
> end = new Date(2014, 9, 31, 23, 59, 59)
Fri Oct 31 2014 23:59:59 GMT-0400 (EDT)
> moment.range(start, end).diff('months')
0
> moment.range(start, end).diff('days')
30
```

**Comment by jiaweihli** [comment]
I get the same output:

```coffeescript
coffee> start = new Date(2014, 9, 1)
Wed Oct 01 2014 00:00:00 GMT-0700 (PDT)
coffee> end = new Date(2014, 9, 31, 23, 59, 59)
Fri Oct 31 2014 23:59:59 GMT-0700 (PDT)
coffee> moment.range(start, end).diff('months')
0
coffee> moment.range(start, end).diff('days')
30
```

**Comment by gf3** [comment]
@jiaweihli excellent—so this leads me to believe the issue is in the coercion from a `Date` to a number with `+` and then back to a `Date`/`Moment` object somewhere

**Comment by gf3** [comment]
@jiaweihli how about:

```node
> new Date('Sat Oct 31 2014 00:00:00').toISOString()
'2014-10-31T04:00:00.000Z'
> new Date('Sat Oct 31 2014 23:59:59').toISOString()
'2014-11-01T03:59:59.000Z'
```

**Comment by jiaweihli** [comment]
```coffee
coffee> new Date('Sat Oct 31 2014 00:00:00').toISOString()
'2014-10-31T07:00:00.000Z'
coffee> new Date('Sat Oct 31 2014 23:59:59').toISOString()
'2014-11-01T06:59:59.000Z'
```

**Comment by gf3** [comment]
this is definitely a timezone issue—the solution is to construct dates using the moment object and lock them to a specific timezone

<img width="813" alt="screen shot 2016-12-12 at 8 44 13 pm" src="https://cloud.githubusercontent.com/assets/18397/21124253/c9480da0-c0ab-11e6-9103-86f072bee8ad.png">
