### ISSUE TITLE
Time ranges

### ISSUE THREAD

**Issue by mokkabonna** [gf3/moment-range#57]
Would be nice to have functionality to check if a date is in a given time range, ignoring date. It does not seem that is possible at the moment.

Something like
```
var time1 = moment('2014-03-02T12:01:00');
var timerange = moment.range.time('12:00', '13:00');
timerange.contains(time1); //=> true
```

or maybe something more generic like this:

```
var time1 = moment('2014-03-02T12:01:00');
var timerange = moment.range('2014-01-01T12:00', '2014-01-02T13:00').ignore('year', 'month', 'day');
timerange.contains(time1); //=> true

```

Or even supply a function to the ignore function and implement some custom range logic.

Could be I'm not considering potential problems here, but wanted to throw it out there as a suggestion.

**Comment by gf3** [comment]
hi @mokkabonna  sorry for the delay (been extremely busy lately), check out [`.contains`](https://github.com/gf3/moment-range#contains--within--overlaps--intersect--add--subtract)

**Comment by gf3** [comment]
hi @mokkabonna sorry for the delay, i'd recommend changing the date of the object you'd like to check against. a change like this would really mess with the underlying assumptions made by this library re: interval math

**Comment by mokkabonna** [comment]
Yeah that's what I ended up doing.
