### ISSUE TITLE
moment-range uses different moment than owner on node.js

### ISSUE THREAD

**Issue by dantman** [gf3/moment-range#58]
Because moment-range requires moment itself the moment object it augments is different than the one you get simply by using `require('moment')`.

Firstly, this means you can't use multiple moment plugins as `moment` because they will be part of different moment objects.

Secondly, this means potential versioning troubles. When you require moment yourself you have a version with a range you define and control. But the `>= 1` means that any version of moment can show up, and if the latest is suddenly incompatible with code you've written, then everything is broken and you can't fix it, because you cannot control moment-range's version.

The simple thing to do is just move moment to devDependencies.

**Comment by gf3** [comment]
hi @dantman sorry for the delay (been extremely busy lately) that's an excellent suggestion, i'll look into it. thank you

**Comment by gf3** [comment]
so it looks like this is related to #54 `moment-range` needs to be able to inject itself into `moment`'s prototype so it can be used. and for this to happen it needs access to the moment object that you're using. currently there isn't a good way of doing this cross-platform

**Comment by Nemo157** [comment]
The node way to do this is to specify `moment` as a `peerDependency`, the application that's using `moment-range` would then have to install `moment` itself and you're guaranteed to be using the same copy of `moment`. If the application were to try installing a version of `moment` that is incompatible with `moment-range`s version specifier for it then there would be a warning when installing. To make development easier you normally put `moment` into `devDependencies` as well so it will be installed when you're working on the library.

**Comment by gf3** [comment]
**Note:** this breaking change was reverted in `1.2.0` and reintroduced in `2.0.0`
