### ISSUE TITLE
To-value in ranges are inclusive, how to make them exclusive?

### ISSUE THREAD

**Issue by mewwts** [gf3/moment-range#61]
Hey guys. Thanks for a cool lib. Simple question. Suppose we have:
```javascript
var dateA = moment('2015-01-04T00:00:00+00:00');
var dateB = moment('2015-01-06T00:00:00+00:00');
```
And we're trying to find the  weekdays in the range that starts on ```dateA``` and ends on ```dateB```.
```javascript
var weekdays = [];
moment()
  .range(dateA, dateB)
  .by('d', function (mom) {
      weekdays.push(mom.isoWeekday());
  });
```
This output will be ```[7, 1, 2]```, while what I'd expected/want is ```[7, 1]```. Currently, my dirty little hack is doing 
```javascript
//...
  moment()
    .range(dateA, dateB.subtract(1, 'ms'))
//...
```
and it provides the desired result. Is there a way to do this without the hack? Would you accept a pull request with functionality along the lines of
```javascript
DateRange.prototype.by = function(range, hollaback, inclusive) {
   ...
}
```
with usage,
```javascript
  // ...
  .by('d', function (mom) {
      weekdays.pus(mom.isoWeekday());
  }, false);
```
This should be backwards compatible, if I'm not mistaken. 

Thanks again. :+1:

**Comment by mewwts** [comment]
I'm implementing this and I guess it boils down to modifying ```.contains```. So much the same as in #60.

**Comment by gf3** [comment]
hi @mewwts sorry for the delay (been extremely busy lately) i'm open to this change, unfortunately i don't have time to implement it anytime soon

**Comment by mewwts** [comment]
Cool @gf3, I prototyped it a few weeks ago, but never got around making it proper and robust. Will take a shot at it and fire off a PR.

**Comment by gf3** [comment]
@mewwts you're amazing, thank you

**Comment by mewwts** [comment]
@gf3 some of the existing test cases are failing for me. I added new test cases for the exclusive ```#contains()``` and ```#by()```, but I guess the last thing one wants is for that to contain bugs, so perhaps we could need more test cases? Feel free to take a look at mewwts/moment-range@c0ac65994f16b17df833f6dfeaab9d440be8a3f6 and see if you feel it's worthy a PR.

**Comment by gf3** [comment]
@mewwts try rebasing the latest version and giving it a shot! thanks

**Comment by mewwts** [comment]
Will do! At work now, so will have to wait until tonight or tomorrow.
