### ISSUE TITLE
Consider "duration()" as an alias of "diff()"

### ISSUE THREAD

**Issue by mezz** [gf3/moment-range#64]
I want to find the intersection of two ranges, and get its duration.
The Readme didn't offer any clues until I read the entire thing carefully to find `diff()`. At first glance I assumed "difference" would be the opposite of "intersection".

Just something small that tripped me up and almost turned me away, hope the feedback is helpful.

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
