### ISSUE TITLE
Can't iterate a range in reverse order

### ISSUE THREAD

**Issue by EvNaverniouk** [gf3/moment-range#68]
I want to iterate over a date range from latest to earliest date, but this doesn't seem to work:

```
var start = moment("2011-11-27", "YYYY-MM-DD");
var end   = moment("2011-04-15", "YYYY-MM-DD");
var range = moment().range(start, end);
range.by('days', function (day) {
    // Never get's called. :(
    console.log(day)
});
```

**Comment by mickdelaney** [comment]
+1

**Comment by gf3** [comment]
how would you feel if moment-range automatically re-arranged your range so that start was always the min and end was always the max?

**Comment by globexdesigns** [comment]
@gf3 I'm not sure how that would help with my issue.

**Comment by gf3** [comment]
@globexdesigns well it would always iterate the correct amount, just not in the reverse order

**Comment by atran** [comment]
+1

**Comment by NGMarmaduke** [comment]
+1

**Comment by nnnnathann** [comment]
+1

**Comment by yozef** [comment]
+1
Maybe we can add an additional parameter 
~~~
range1.by('d', function (moment) {
  acc.push(moment)
}, true, false); // false is the order in reverse, true would be searching forward.
~~~

**Comment by gf3** [comment]
adding discrete methods for reverse iteration in v3, you can follow the progress here: https://github.com/gf3/moment-range/tree/3-dev

example usage [here](https://github.com/gf3/moment-range/blob/1a5fe1f65ecaf36b5d7fe41444af2bbff8b5751b/lib/moment-range_test.js#L285-L294)

thanks for your patience everyone

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
