### ISSUE TITLE
ReadMe Typo

### ISSUE THREAD

**Issue by dcjohnston** [gf3/moment-range#71]
```
"Find out if your moment falls within a date range:

var start = new Date(2012, 4, 1);
var end   = new Date(2012, 4, 23);
var when  = moment("2012-05-10", "YYYY-MM-DD");
var range = moment().range(start, end);

when.within(range); // true"
```
Should evaluate to false, no?

**Comment by fonini** [comment]
In JavaScript, the first month is 0 (zero). 
So, when you write ````new Date(2012, 4, 1)````, the actual date is 2012-05-01.

**Comment by dcjohnston** [comment]
I'm too used to using moment now :p. Sorry for the misunderstanding.
