### ISSUE TITLE
Bug with Overlap on a one day range

### ISSUE THREAD

**Issue by DoryZi** [gf3/moment-range#73]
Hi,
I found that when you run an overlap with one range and another range that has one day range and matches the end of the other range, overlap returns false, when it should return the overlap section:

var rangeA = moment.range("15-5-2015","20-5-2015");
var rangeB = moment.range("20-5-2015", "20-5"2015);
rangeA.overlap(rangeB) --> returns false.

The fix is simple:
change line 134:
from 
 } else if (((this.start <= (_ref7 = other.start) && _ref7 < (_ref6 = other.end)) && _ref6 <= this.end)) {

to 

 } else if (((this.start <= (_ref7 = other.start) && _ref7 <= (_ref6 = other.end)) && _ref6 <= this.end)) {
                                                                                    ^^^
                                                         the range end date can be exactly like the start date.

**Comment by gf3** [comment]
hmm, i'm not getting the same output:

``` javascript
var rangeA = moment.range("2015/5/15", "2015/5/20");
// undefined
var rangeB = moment.range("2015/5/20", "2015/5/20");
// undefined
rangeA.overlaps(rangeB)
// true
```

**Comment by marg51** [comment]
The cause is the date format "15-5-2015". It returns _Invalid Date_ with moment

```javascript
moment("15-5-2015")._d
// Object:Invalid Date
```

**Comment by gf3** [comment]
ahh, good catch! thank you
