### ISSUE TITLE
Stagger ranges?

### ISSUE THREAD

**Issue by SoHiggo** [gf3/moment-range#75]
I see no obvious way to stagger a range.

For example, rather than have an entire range in incremental fashion, it would be preferable to leave specific dates out in the iteration. For example:

Exclude fridays and sundays

**Comment by gf3** [comment]
@SoHiggo what would the API for  something like this look like?

**Comment by SoHiggo** [comment]
Something like this:

    var start = new Date(year, startMonth);
    var end = new Date(year, endMonth);
    var range = moment().range(start, end);
    
    var remove = range.remove('friday','sunday');

    // Where `remove()` would remove any such days in the range

**Comment by gf3** [comment]
@SoHiggo interesting. and what would the use case be for a feature like this?

**Comment by SoHiggo** [comment]
I need it for my own reasons, but I think others would find it useful.

Perhaps there is a way to do this using some other method outlined in the readme?

**Comment by gf3** [comment]
@SoHiggo maybe if you explain to me what you're trying to accomplish i can provide you with a solution?

**Comment by SoHiggo** [comment]
Okay. Below is the code I have:

    var start = new Date(2015, 0),
    end = new Date(2020, 11),
    range = moment().range(start, end);

Now if there was some way to exclude certain days?

**Comment by gf3** [comment]
@SoHiggo depending on what you're building you could do something like this:

``` javascript
var start = new Date(2015, 0);
var end = new Date(2020, 11);
var range = moment().range(start, end);

// Exclude weekends
range.by('day', function(m) {
  if (m.day() == 0 || m.day() == 6) { return; }
  // Do your thing...
});
```

**Comment by SoHiggo** [comment]
That's great.

I've been doing something similar. I just thought there was some inbuilt way of doing that using the plugin you wrote. It's not much of an issue, and I can achieve my goal.

BTW Thanks for this plugin, it is very helpful.

**Comment by gf3** [comment]
@SoHiggo glad i could help, feel free to contact me if you have any further questions
