### ISSUE TITLE
"moment.locale is not a function" error and "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by dubert** [gf3/moment-range#77]
Using 1.1.0.

For some reason moment-range is not able to perform many of the basic functions that moment can.

Before 1.1.0:
- One could call `moment()` to get the current time and date in a moment instance, but now that produces: "Cannot read property 'length' of undefined" because it does not have any arguments.
- One could define the locale by calling moment.locale(...) but now that produces the error: "moment.locale is not a function"

Do moment and moment-range need to be declared separately and moment-range called exclusively for ranges and moment called for everything else?

**Comment by gf3** [comment]
hi @dubert can you provide me with a code sample so i can reproduce the issue? also are you using moment-range in the browser or node/io?

**Comment by dubert** [comment]
Using through npm.

If you look at the example in https://github.com/dubert/react-kronos and update moment-range to 1.1.0, it will produce both of these errors.

**Comment by gf3** [comment]
@dubert can you give it a shot with `1.1.2` and let me know if it's all fixed?

**Comment by gf3** [comment]
ahh, i see the issue.

**Comment by gf3** [comment]
@dubert should be fixed in [1.2.0](https://github.com/gf3/moment-range/releases/tag/1.2.0)

**Comment by dubert** [comment]
Thanks @gf3 !
