### ISSUE TITLE
Ranges with times - including borders

### ISSUE THREAD

**Issue by kayz1** [gf3/moment-range#80]
``` javascript
var from = moment('2015-06-01 00:00:00.000', 'YYYY-MM-DD HH:mm:ss.SSS');
var to = moment('2015-06-01 23:59:59.999', 'YYYY-MM-DD HH:mm:ss.SSS'); // same day
var currentRange = moment.range(from, to);

currentRange.contains(moment('2015-06-01 00:00:00.000', 'YYYY-MM-DD HH:mm:ss.SSS')); // should be true
currentRange.contains(moment('2015-06-01 01:00:00.000', 'YYYY-MM-DD HH:mm:ss.SSS')); // should be true
currentRange.contains(moment('2015-06-01 23:59:59.999', 'YYYY-MM-DD HH:mm:ss.SSS')); // should be true
```

How can I achieve something like that?

**Comment by gf3** [comment]
hi @kayz1, these all seem to be `true` for me using the latest moment-range:

![screen shot 2015-06-03 at 3 43 32 pm](https://cloud.githubusercontent.com/assets/18397/7969799/6285787a-0a07-11e5-9823-321538bbb78d.png)

**Comment by kayz1** [comment]
In the browser I get this results:
from: 2015-06-01 00:00:00.000
to: 2015-06-01 23:59:59.999

Contains?
2015-06-01 00:00:00.000 // false
2015-06-01 11:10:00.000 // true
2015-06-02 08:00:00.000 // false
2015-06-02 00:00:00.000 // true
2015-06-03 00:00:00.000 // false

**Comment by gf3** [comment]
@kayz1 which browser and moment-range version are you using? this is what i'm getting using moment-range `2.0.0` in Firefox:

![screen shot 2015-06-04 at 11 19 19 am](https://cloud.githubusercontent.com/assets/18397/7987455/963755ae-0aab-11e5-82a2-048a2b4727a0.png)

**Comment by gf3** [comment]
can't reproduce. please reopen this if it still isn't resolved for you
