### ISSUE TITLE
Document the NULL return value of #intersect when the two ranges don't intersect

### ISSUE THREAD

**Issue by VanTanev** [gf3/moment-range#82]
There is no mention in the documentation that #intersect returns `null` when the two ranges don't intersect. This can lead to unexpected results.

**Comment by gf3** [comment]
thanks! [added here](http://gf3.github.io/moment-range/DateRange.html#intersect)

**Comment by VanTanev** [comment]
Thanks, though I think it would be good to also have this information in the README.
