### ISSUE TITLE
major bump for refactoring to ES6

### ISSUE THREAD

**Issue by rovolution** [gf3/moment-range#84]
To whomever it may concern,

First of all, I want to say thank you for creating this awesome plugin!

When I first installed this dependency into my project, I downloaded the `1.0.7` version.

In my package.json, I set the version number to be `^1.0.7`, which means I will accept any minor or patch updates, but no major updates.

Recently, you made a change to use ES6 syntax (which is awesome and I am all for that), however, according to semver conventions, I would consider that a major change and therefore necessitate a major version bump. Ended up breaking my compatibility for non ES6 compliant browsers.

[See this document for more info on semver](http://semver.org/)

**Comment by gf3** [comment]
hi, @rovolution, although i've started using ES6 i am also including a transpiled ES3 version which is the default for npm and bower. there shouldn't be any compatibility issues on your end (if there are it's probably a bug). you'll want to make sure that you're using `1.2.0`, though

**Comment by rovolution** [comment]
@gf3 I believe [this commit](https://github.com/gf3/moment-range/commit/6b9c50c018444ed309eb24c3d75559dea9e2550a) should resolve my issue. Thanks!
