### ISSUE TITLE
Subtract returns undefined?

### ISSUE THREAD

**Issue by Janpot** [gf3/moment-range#86]
I'm running into an issue when subtracting an empty range:

```js
var o = moment.range('2015-04-07T00:00:00+00:00/2015-04-08T00:00:00+00:00');
var s = moment.range('2015-04-07T17:12:18+00:00/2015-04-07T17:12:18+00:00');
o.subtract(s);
// returns undefined
```

If I understand correctly this should return an array instead.

**Comment by gf3** [comment]
fixed and published in [`2.0.3`](https://github.com/gf3/moment-range/releases/tag/2.0.3), thank you!
