### ISSUE TITLE
Using recurring date ranges 

### ISSUE THREAD

**Issue by florianbepunkt** [gf3/moment-range#90]
Hey, I wondered whether it possible to create ranges that are year agnostic…like having a date range for example from August 1st until 20th and then check whether a specific date falls into that range.

My use case: I'm working on a booking system. Users create date ranges which are linked to ticket prices… these ranges are not valid for a specific year but for future years as well.

Thanks,
Florian

**Comment by gf3** [comment]
unfortunately this is not possible as moment-range uses date/moment objects under the hood which are fixed to a point in time

**Comment by luke-hawk** [comment]
Hi @florianbepunkt,
may I ask how you ended up solving your issue? I'm stuck on a similar case and tried to use [moment-recur](https://github.com/c-trimm/moment-recur) for the recurrence part, but wasn't able to make it work with moment-range. Any advice highly appreciated! Cheers:)

**Comment by florianbepunkt** [comment]
@luke-hawk Honestly, I don't remember… I think we ended up with a rather scruffy solution where we parsed month and day and used this as a comparioson.

const rangeStart = parseInt(moment().startOf('month').format('MMDD'));
const rangeEnd = moment().endOf('month').format('MMDD');

const someDateInBetween = parseInt(moment().format('MMDD'));

const isInBetween = (date) => {
}
