### ISSUE TITLE
Range overlaps on boundaries?

### ISSUE THREAD

**Issue by lowi** [gf3/moment-range#92]
1. When the end of a range is equal to the start of the next range, shouldn't it overlaps?
   rangeA = moment().range(moment('2015-09-15'), moment('2015-09-16'))
   rangeB = moment().range(moment('2015-09-16'), moment('2015-09-17'))
   
   rangeA.overlaps(rangeB); // false
   rangeB.overlaps(rangeA); // false
2. Also rangeA.add(rangeB) does not extend rangeA

**Comment by YagoQuinoy** [comment]
+1

**Comment by YagoQuinoy** [comment]
+1

**Comment by coosmiin** [comment]
yes, yes and yes

**Comment by echogame** [comment]
+1

**Comment by DanielSundberg** [comment]
I would have to disagree. At least when using date and time I think this is correct behavior. The library I use on my backend (TimePeriodLibrary.Net, http://www.codeproject.com/Articles/168662/Time-Period-Library-for-NET) behaves this way.

**Comment by gf3** [comment]
great suggestions, i've added both an [`#adjacent`](https://github.com/gf3/moment-range/blob/25be063e539de84f1e4884b776a9bb0a10d9f52f/lib/moment-range.js#L52-L57) method and an [`adjacent option to #overlaps`](https://github.com/gf3/moment-range/blob/25be063e539de84f1e4884b776a9bb0a10d9f52f/lib/moment-range.js#L193-L201) in the upcoming release

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
