### ISSUE TITLE
.toArray

### ISSUE THREAD

**Issue by honzajavorek** [gf3/moment-range#95]
I think a `toArray` convenience method would be useful. Quite often one needs to have the range as array and work with it later, not iterating over it right away.

```js
function toArray(by) {
  by = by || 'days';
  var acc = [];
  this.by(by, function(unit) {
    acc.push(unit);
  });
  return acc;
}
```

**Comment by jacek-dargiel** [comment]
I think this is very important. This would be excellent in functional programming, ie:
```
let total = range.toArray('days')
.map(day => day.format('YYYY-MM-DD'))
.map(day => getDailyCost(day))
.reduce((sum, cost) => sum + cost);
```

I'll try to make a PR for this later today.

**Comment by tb** [comment]
+1

**Comment by jonathanong** [comment]
:+1:

**Comment by JGantner** [comment]
+1
