### ISSUE TITLE
Update examples for node

### ISSUE THREAD

**Issue by felixfbecker** [gf3/moment-range#98]
The example for Node/NPM shows this:

``` js
var moment = require('moment');
require('moment-range');
```

making it seem like the way to go for Node users is to require() this module so it monkey-patches itself on moment. This may be the best way in browser, but is a bad practice in Node.
In your changelog you promote:

``` js
var moment = require('moment');
var DateRange = require('moment-range');
```

This should be the example for Node.

**Comment by gf3** [comment]
updated in the upcoming `3.0.0` release → https://github.com/gf3/moment-range/blob/da7da21ca4b5a6293078a0189caebec5b7c48120/README.md#node--npm

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
