### ISSUE TITLE
Uncaught TypeError: Identifier 'moment' has already been declared

### ISSUE THREAD

**Issue by hiddenpearls** [gf3/moment-range#99]
Who do I get this error message ?

Uncaught TypeError: Identifier 'moment' has already been declared

**Comment by Leapfrognz** [comment]
Getting this issue as well.

**Comment by maxflex** [comment]
The same issue

**Comment by mkutscher** [comment]
Maybe use the moment-range.js from the dist folder instead of the lib folder (which seems to be the npm module)

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
